language: python
python:
 - "2.7"

# install requirements
install:
 - pip install -r requirements.txt

# Build with unit tests and coverage
# script: add proper script command here and un-comment
# NOTE: This section MUST be fixed before integrating Travis

# safelist
branches:
  only:
  - master # For all work approved for release
  - develop # For general development work

# Post-steps for successful builds
after_success:
 coveralls